# Generated by Django 4.2.3 on 2023-09-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_remove_empleado_avatar_empleado_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
