# Generated by Django 4.2.3 on 2023-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen1', models.CharField(blank=True, max_length=254)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
